In [5]:
import numpy as np

In [6]:
arr=np.array([12,23,45,56,32])


In [7]:
arr

array([12, 23, 45, 56, 32])

In [6]:
print(arr)

[12 23 45 56 32]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.dtype

dtype('int32')

In [15]:
arr=np.array([12,34,56,78.67,77])

In [16]:
arr.dtype

dtype('float64')

In [17]:
arr

array([12.  , 34.  , 56.  , 78.67, 77.  ])

In [20]:
arr=np.array([12,34,56,67,77,'pune'])

In [21]:
arr

array(['12', '34', '56', '67', '77', 'pune'], dtype='<U11')

In [22]:
arr=np.array([12,34,56,78.67,77,'pune'])

In [23]:
arr

array(['12', '34', '56', '78.67', '77', 'pune'], dtype='<U32')

In [8]:
import numpy as np
import timeit

code_snippet="""
arr=np.array([12,34,45,67,66,22,'pune'])"""

execution_time=timeit.timeit(stmt=code_snippet,setup="import numpy as np",number=1)


print("Execution time:", execution_time)

Execution time: 3.1599949579685926e-05


In [29]:
arr

array(['12', '34', '56', '78.67', '77', 'pune'], dtype='<U32')

In [30]:
arr[3]

'78.67'

In [31]:
arr.shape

(6,)

In [32]:
import numpy as np
arr=np.array([12,23,34,45])
print(arr)

[12 23 34 45]


In [33]:
arr*2

array([24, 46, 68, 90])

In [37]:
import numpy as np
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
import numpy as np
arr=np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


In [39]:
import numpy as np
arr=np.arange(-5,5.5,0.5)
print(arr)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5. ]


In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
#2d

In [44]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [45]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
arr1.shape

(4, 3)

In [47]:
arr1.ndim

2

In [48]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr1.reshape

<function ndarray.reshape>

In [52]:
arr1.size

12

In [53]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [55]:
arr1.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [56]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [60]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [61]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
arr1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [63]:
arr1.mean()

6.5

In [66]:
arr1=np.array([1,2,3,4,5,6,7])

In [67]:
np.unique(arr)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [72]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [73]:
np.linalg.det(arr1)

-9.51619735392994e-16

In [74]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [75]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [76]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])